# Generated by Django 3.1.7 on 2021-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poupular_destination',
            name='destination_days',
            field=models.IntegerField(default=0),
        ),
    ]
