# Generated by Django 3.1.7 on 2021-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210526_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_destination',
            name='trip_drive_link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
