# Generated by Django 3.1.7 on 2021-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_travel_destination_trip_drive_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_destination',
            name='trip_drive_link',
            field=models.CharField(max_length=250),
        ),
    ]
