# Generated by Django 3.1.7 on 2021-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trek',
        ),
        migrations.AlterField(
            model_name='travel_destination',
            name='trip_choice',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Trending Trips', 'Trending Trips'), ('Popular Trips', 'Popular Trips'), ('Treks', 'Treks')], default='Choose', max_length=50),
        ),
    ]
