# Generated by Django 3.1.7 on 2021-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210528_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='', upload_to='tnt/images')),
                ('blog_title', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.ImageField(default='', upload_to='tnt/images')),
                ('blog_description_short', models.TextField(blank=True)),
                ('blog_description', models.TextField(blank=True)),
                ('blog_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
