# Generated by Django 3.1.7 on 2021-05-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
