# Generated by Django 3.1.7 on 2021-05-28 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210528_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_description_short',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
