# Generated by Django 3.1.7 on 2021-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(default='', upload_to='tnt/images')),
                ('gallery_title', models.CharField(max_length=100)),
            ],
        ),
    ]
