# Generated by Django 3.1.7 on 2021-06-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210606_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel_Destination',
        ),
    ]
