# Generated by Django 3.1.7 on 2021-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_travel_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBookingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_number', models.IntegerField(default=0)),
                ('customer_payment', models.IntegerField(default=0)),
                ('customer_payment_status', models.CharField(choices=[('c', 'Confirmed'), ('p', 'Pending')], max_length=1)),
            ],
        ),
    ]
