# Generated by Django 3.1.7 on 2021-06-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_customerbookingdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerBookingData',
        ),
    ]
