# Generated by Django 3.1.7 on 2021-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_delete_customerbookingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_destination',
            name='trip_choice',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Trending Trips', 'Trending Trips'), ('Weekend Trips', 'Weekend Trips'), ('Backpacking Trips', 'Backpacking Trips'), ('Treks', 'Treks')], default='Choose', max_length=50),
        ),
    ]
